### ISSUE TITLE
an idea for requirements.txt

### ISSUE THREAD

**Issue by mmDzre** [vfarid/cf-ip-scanner-py#10]
please add all the packages(even standard packages that have imported to the script) to the `requirements.txt` and tell the users to use `pip install -r requirements.txt` to install all the packages at once. even those installed packages won't make any error, pip will skip them without confusing the user.
btw thank you Vahid.
خرّم آن کس که در این محنت گاه///خاطری را سبب تسکین است//صائب

**Comment by nimaafallah** [comment]
اقا این از یچیزی ایراد میگیره رو ورژن جدیش.. ایشونم فکر کنم وقت نمیکنن پاسخ بدن.
PS C:\1cf> py .\start.py
Traceback (most recent call last):
  File "C:\1cf\start.py", line 14, in <module>
    import curses
  File "C:\Users\NIMA\AppData\Local\Programs\Python\Python310\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'

**Comment by nimaafallah** [comment]
in Module ro chetori bayad nasb konam : curses

ro win 11 mikham run konam

**Comment by vfarid** [comment]
Thanks, i added requirements.txt in v1.5 but still there is an issue for windows specific packages :/
