### ISSUE TITLE
doesnt show result table on win 11 and python 3.11

### ISSUE THREAD

**Issue by nickali2** [vfarid/cf-ip-scanner-py#12]
after running the script, it shows that some ip have acceptable ping but doesn't show result table.
python 3.11
win11
powershell7.3

![image](https://user-images.githubusercontent.com/23019220/229574497-de9602c7-ebdc-40fc-b87e-5cff07473b0a.png)

**Comment by Morteza561** [comment]
![Screenshot 2023-04-08 111912](https://user-images.githubusercontent.com/5309629/230710246-a18af9ba-9bff-422a-ab0c-cce9163cf963.png)
The same is going on windows 11, script version 1.5

**Comment by Morteza561** [comment]
![Screenshot 2023-04-09 115405](https://user-images.githubusercontent.com/5309629/230762376-5dd26a75-aea7-43fa-9a7c-5a0fc1ac58a5.png)
It seems the problem is in _getLatencyAndJitter_ function. The above result is generated after commenting out this function!

**Comment by Morteza561** [comment]
@vfarid

**Comment by vfarid** [comment]
There is no issue with the function. Maybe you need to increase min values based on your internaet speed and operator limit for cloudflare.
