### ISSUE TITLE
import curses

### ISSUE THREAD

**Issue by mujsou** [vfarid/cf-ip-scanner-py#13]
متاسفانه هنگام اجرا این ارور رو میده
Traceback (most recent call last):
  File "C:\ip\cf-ip-scanner-py-main\start.py", line 14, in <module>
    import curses[](url)
![image](https://user-images.githubusercontent.com/94400519/229643845-6b044245-0b0c-4d7d-b630-48fc9a608999.png)

**Comment by nickali2** [comment]
> متاسفانه هنگام اجرا این ارور رو میده Traceback (most recent call last): File "C:\ip\cf-ip-scanner-py-main\start.py", line 14, in import curses ![image](https://user-images.githubusercontent.com/94400519/229643845-6b044245-0b0c-4d7d-b630-48fc9a608999.png)

execute this command: pip install windows-curses
