### ISSUE TITLE
run-output Bug in script

### ISSUE THREAD

**Issue by vahidiano** [vfarid/cf-ip-scanner-py#14]
توو ورژن 1.3که اسکریپت ران میشد  تعداد پارامتر خروجی ای‌پی تمیز که داده میشد،به عنوان مثال 4ای‌پی اسکریپت میومد بر اساس کل ای‌پی ها هرکدوم با مقداری که ست شده همخوانی داشت خروجی میداد از اون چند میلیون ای‌پی
اما توو ورژن 1.4باز هیچ خروجیی داده نمیشه.تمام لایبری ها requests.ping3 نصب شده
مقادیر وارده به شرح زیر هست و پارامترا ورودی یک چیز معقوله و بازم خروجی نداره
Enter max IP [4]:
Enter max ping [200]:
Enter max jitter [100]:
Enter max latency [300]:
Enter IPs to include (comma seperated, '-' to ignore) [104,172,162]:
Enter IPs to exclude (comma seperated, '-' to ignore) []:
Enter test data size in KB [1024]:
Enter minimum download speed (Mbps) [0.3]:
Enter minimum upload speed (Mbps) [0.1]:
Do you want to upload the result to your Cloudflare subdomain (yes/no) [n]?

**Comment by vfarid** [comment]
روی ویندوز مشکل openssl وجود داشت که تو نسخه ی ۱.۵ رفع شد.
