### ISSUE TITLE
Some UX improvements - I/O

### ISSUE THREAD

**Issue by iran-free-net** [vfarid/cf-ip-scanner-py#16]
**1) Let user to import custom CIDR in absolute path by anyname (to let user customize CIDR for any isp) and store it config file**
   2) Show results in tabular outputs like what it shows in terminal
   3) Just shows a simple question to change predefined configs
   4) Let user load extra configs absolute to /configs/lablablab.ini and just type the name of config
   5) Let user export result in absolute /output/ or /export or something like it in another name like "shatel.txt"
   6) Let user to set order by result but set
   7) Let user to re-test founded ips to check stability
   8) Prepend founded ip to tabular data result vice versa for more readability

**Comment by iran-free-net** [comment]
9) Also if its possible set a shortcut to let user pause and resume scan

**Comment by vfarid** [comment]
1) In the main branch, there is a text file containing IP Ranges, you may customize it.
2) Not clear what you mean.
3-5) May be done in next updates.
6) Refer to 8
7) It is planned for next update
8) As of v1.5 the result will not sorted during the search and it will be sorted just befor writing to file.
9) Not planned for now, i dont know what is its usage.
10) It may have a performance issue. Not for now.
11) Refer to 7

Next time, it is recomended to send an specific request in a seperate issue so i can keep it open until implementation of needed change.
