### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'fileno'

### ISSUE THREAD

**Issue by behzadawesome** [vfarid/cf-ip-scanner-py#18]
salam
mogheie ejra in khata ro mide

![00](https://user-images.githubusercontent.com/25481740/230615100-5c58ed7c-e48d-4580-88dc-0193c3153575.jpg)

**Comment by vfarid** [comment]
لطفا خطا رو کامل بفرستید و پلتفرم و نسخه‌ی پایتون رو هم بنویسید.
