### ISSUE TITLE
پاک کردن رکورد های dns  روی ساب دامنه

### ISSUE THREAD

**Issue by Dementora** [vfarid/cf-ip-scanner-py#2]
ممنون از ابزار کارآمدی که ساختین یه مشکلی برای پیش اومد که گفتم اینجا بگم بقیه استفاده کنن من اونجایی که ساب دامین میخواست فقط ساب دامین رو نوشتم بدون خود دامنه اصلی  ایپی ها اد شدن و مشکلی نداشت ولی رکورد های قبلی روی سابدامین پاک نمیشدن کامل که نوشتم درست شد اینطوری ip.example.com

**Comment by Dementora** [comment]
فک کنم مشکل از record["id"] توی خط 246 باشه چون مثلا من سه تا ایپی ست کردم رو ساب دامنه ip خودم که هرکدوم از dns record  هاش منحصر به فرده و id خاص خودش رو داره

**Comment by vfarid** [comment]
متشکرم. براش یه validation اضافه کردم.
