### ISSUE TITLE
عدم نمایش ای پی 

### ISSUE THREAD

**Issue by omidmj** [vfarid/cf-ip-scanner-py#24]
سلام وحید جان بعد تمامی موارد که تو نیازمندی فایل بود نصب کردم برنامه که استارت میزنم همه چیز رو روی حالت پیش فرض خودتت قرار میدم حتی تعداد ای پی میذارم 1 دونه ولی حتی یکدونه هم نمایش نمیده در حالی که موقع اسکن بعضی ای پی ها زیرش مینوسه پینگشون رو ولی ثبت نمیکنه بالغ بر 2 هزار خورده ای ای پی تست کرد ولی یک دونه هم پیدا نکرد مشکل به نظرت کجاست؟

**Comment by TiamaaShah** [comment]
برای من هم تا 2 روز پیش کار میکرد ,ولی از دیشب به همین مشگل خوردم هیچی آیپی پیدا نمیکنه

**Comment by TiamaaShah** [comment]
من در چند هفته گذشته همش با همین برنامه آی پی پیدا میکردم، پس اشکال از نصب نیست.

**Comment by omidmj** [comment]
> اشکال ازت سرعت تاخیر هستش دیگه زیر 500 پیدا نمیکنه, باید تو تنظیمات بزاریش روی 1000
> 
> Latency : 1000

تست میکنم ببینم چی جواب میده

**Comment by vfarid** [comment]
مشکل به دلیل همین محدودیت‌های جدیده. وقتی پیدا کنه حتما تو جدول مینویسه. اینهایی که میبینید مینویسه ولی به جدول اضافه نمیشه تو مرحله‌ی تست آپلود حذف میشن.
