### ISSUE TITLE
گزینه برای حزف تست آپلود

### ISSUE THREAD

**Issue by TiamaaShah** [vfarid/cf-ip-scanner-py#25]
سلام

اگه می‌شه یه گزینه بذارید برای حذف تست آپلود چون من اینترنتم سرعتش ۱۶ هستش ولی‌ آپلود تا ۱ هم نمیرسه و وقتی‌ میخوام دقت تست برنامه رو بالا ببرم مجبورم حجم تست رو تا ۱۵ مگابایت بالا ببرم و سر هر تست چون می‌خواد ۱۵ مگابایت آپلود کنه چند دقیقه طول میکش ولی‌ دانلود رو در جا تست می‌کنه. فکر کنم این مشکل برای همه کسانی‌ که‌ (ای دی اس ال) دارن پیش بیاد.
یا اینکه تعیین حجم تست آپلود رو از دانلود جدا کنید.
با تشکر از این برنامه خوبتون

**Comment by vfarid** [comment]
Planned for next release

**Comment by freenet202301** [comment]
مال مرتضی باشسیز این گزینه رو داره 

https://pypi.org/project/cfscanner/

**Comment by aboozar1368** [comment]
سلام چجوری می تونیم کانفگیگ خودمونو اضافه کنیم

**Comment by mzarchi** [comment]
> سلام چجوری می تونیم کانفگیگ خودمونو اضافه کنیم

کد رو fork کن بعدش pr بزن در صورت تایید merge میشه

**Comment by Hamid7872** [comment]
تو اون قسمتی که ازت حداقل تست سرعت آپلود رو میخواد 0 بزن والسلام :|

**Comment by vfarid** [comment]
در نسخه‌ی main میتونید با وارد کردن عدد صفر به جای minimum download speed و یا minimum upload speed تست مربوطه رو غیر فعال کنید.
