### ISSUE TITLE
افزودن رنج ای پی به صورت دستی

### ISSUE THREAD

**Issue by sh-vp** [vfarid/cf-ip-scanner-py#30]
سلام وقت بخیر
امکانش هست قابلیت اسکن بر روی رنج اختصاصی و یا افزودن یک رنج خاص به لیست ای پی های اسکنر رو فراهم کنید
این مورد خیلی میتونه به دوستان برای راحت تر شدن اسکنشون کمک بکنه

با سپاس فراوان از بابت زحمات بی دریغ شما

**Comment by Hamid7872** [comment]
با ابزار vim میتونین فایل ipv4.txt رو ویرایش کنین
