### ISSUE TITLE
اضافه کردن فایل run.bat

### ISSUE THREAD

**Issue by arashkey** [vfarid/cf-ip-scanner-py#32]
یک فایل برای اینکه ویندوزی ها بتونن راحت تر از برنامه استفاده کنن اضافه کردم به نام run.bat که همینجا براتون ارسال می کنم اگر صلاح دونستید به پروژه اضافه کنید. کارش اینکه تمامی نیازمندی های پروژه رو بره دانلود کنه یا راهنمایی تون کنه از کجا می تونید دانلودش کنید

و برای اینکه بتونید تمامی ساب دامنه های اضافه شده بوسیله برنامه رو هم حذف کنید، همون فایل اصلی برنامه رو یکم تغییر دادم به نام deleteAll.py که اونم ارسال می کنم(خیلی خوب نشد ولی کار رو در میاره :-) )

[extended files.zip](https://github.com/vfarid/cf-ip-scanner-py/files/11642635/extended.files.zip)
با تشکر از برنامه خوبتون

**Comment by vfarid** [comment]
سلام و تشکر. چنین موردی رو باید pull request بزنید تا امکان بررسی و الحاقش به کد وجود داشته باشه.
متشکرم
