### ISSUE TITLE
اسکنر قبل از شروع به اسکن آی پی ها متوقف میشود

### ISSUE THREAD

**Issue by KohanTorabi** [vfarid/cf-ip-scanner-py#35]
من با ویندوز 11 وقتی اسکنر رو ران میکنم بعد از شافل کردن خود به خود متوقف میشود.

![image](https://github.com/vfarid/cf-ip-scanner-py/assets/46380696/359d62f4-a629-4cb9-b344-eb84a796380c)

**Comment by vfarid** [comment]
احتمالا مشکل ram داره. تو بخش include رنج آی‌پی بدید بهش که مجبور نباشه تمام رنج‌ها رو اسکن کنه.

**Comment by KohanTorabi** [comment]
رنج آی پی هم دادم ولی فرقی نکرد:

![image](https://github.com/vfarid/cf-ip-scanner-py/assets/46380696/bd1065d4-a239-4d73-baec-b98afbb9bdad)
