### ISSUE TITLE
selectd_ip_list, total_test = curses.wrapper(startTest, ip_list=ip_list, config=config)

### ISSUE THREAD

**Issue by arashkey** [vfarid/cf-ip-scanner-py#38]
روز بخیر
توی ویندوز اجراش می کنم سر این خط مشکل پیدا میکنه، ترای هم گذاشتم ولی خطای نمایش نمیده و می پره بیرون

`
selectd_ip_list, total_test = curses.wrapper(startTest, ip_list=ip_list, config=config)
`

**Comment by arashkey** [comment]
روی نسخه قبلی هم درست کار نمیکنه. البته همه پکیج های زیر مجموعه رو یکبار پاک کردم دوباره نصب کردم

```
pip uninstall -r requirements.txt
pip install -r requirements.txt
```

python --version
Python 3.12.0

pip --version 
pip 24.0

**Comment by vfarid** [comment]
روی ویندوز باید windows-curses رو نصب کنید

**Comment by arashkey** [comment]
روز بخیر، و ممنون بابت راهنمایی تون، 
نصب کردم ولی متاسفانه فرقی نکرد.

pip uninstall curses
WARNING: Skipping curses as it is not installed.

**Comment by arashkey** [comment]
البته به نظر میاد افراد دیگه هم به همین مشکل خوردن
https://github.com/vfarid/cf-ip-scanner-py/issues/35

**Comment by vfarid** [comment]
اون مشکل #35 با مورد شما فرق داره، شما باید پکیجی که گفتم رو نصب کنید:
pip install windows-curses

**Comment by arashkey** [comment]
من نصب کردم به جان خودم ولی فایده ای نداره، بازم همون خطا رو می گیرم. برنامه اجرا می شه ولی به اون خط که می رسه دیگه جلو نمی ره ، میخواهید id تلگرام بدید بهتون anydesk بدم خودتون ببینید 
```
pip install windows-curses
Requirement already satisfied: windows-curses in c:\users\arash\appdata\local\programs\python\python312\lib\site-packages (2.3.2)
```
