### ISSUE TITLE
مشکل در اجرا

### ISSUE THREAD

**Issue by godcracker7921** [vfarid/cf-ip-scanner-py#4]
سلام موقع اجرای برنامه ارور میگیرم متن ارور اینه

    import ping3
ModuleNotFoundError: No module named 'ping3'

فایلو باز کردم و ping3 رو کلا پاک کردم اوکی شد ولی فک کنم ی دلیلی داشته اینو اضافه کردین ممنون میشم فیکسش کنید

**Comment by erfan226** [comment]
سلام، باید پکیجش رو نصب کنید.
pip3 install ping3
