### ISSUE TITLE
سایر کانفیگ ها

### ISSUE THREAD

**Issue by solikh800** [vfarid/cf-ip-scanner-py#6]
سلام و تشکر

چطور میشه کانفیگ vless اضافه کرد. 
من وقتس تو ارایه یه نمونه تنظم تروجان یا ویلس جی ار پی سی میزارم چیزی پیدا نمیکنه
البته دامنه رو چک کردم با ساب مشکلداره
خود کانفیگ چیز خاصی داره ؟

چون من نمونه کانفیگ وی تو ری اکانت شخصیمو گزاشتم

**Comment by vfarid** [comment]
سوالتون مرتبط با این کد نیست. اینجا ما اصلا کاری به کانفیگ نداریم. فقط آی‌پی داره تست میشه.
اگه مورد دیگه ای هست در توییتر رو توییت مرتبطش منشن بدید بررسی کنم.
