### ISSUE TITLE
Real-time result save

### ISSUE THREAD

**Issue by parsahatami98** [vfarid/cf-ip-scanner-py#7]
ممنون برای برنامه خوبی که نوشتین
یه ایده داشتم که به صورت ریل تایم نتایج رو هم به یه فایل اضافه کنه ؛ هر موقع ایپی جدید پیدا شد append کنه به فایل

**Comment by parsahatami98** [comment]
البته نمیدونم شاید مشکل از سیستم من باشه
هنگام استفاده از اسکریپت api کلاودفلیر استفاده نکردم 
بعدش ورژن پایتون ۳.۱۰.۵ 
پیپ و library های ping3 و requests اخرین ورژن
ولی مثل فیلم ایپی هارو نشون نمیده 
اگه به صورت فایل هم ذخیره میکرد خیلی بهتر میشد

**Comment by vfarid** [comment]
Fixed in v1.5
